# Exported from Render on 2025-07-29T16:49:09Z
services:
- type: web
  name: Abhishek-Maurya
  runtime: python
  repo: https://github.com/Abhi956967/Duplicate-Question-Pairs-Detection-Project
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  autoDeployTrigger: commit
version: "1"